services:
  eshopdb:
    image: postgres
    
  distributedcache:
    image: redis
    
  seq:
    image: datalust/seq:latest
    
  messagebus:
    image: rabbitmq:management
    
  identity:
    image: quay.io/keycloak/keycloak:26.1.1
    
volumes:
  postgres_data:
