services:
    eshopdb:
      container_name: eshopdb
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=EShopDb
      restart: always
      ports:
        - "5434:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data